services:
  astro:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    stdin_open: true
    tty: true
